export const ADMIN_LIST_REQUEST = "ADMIN_LIST_REQUEST";
export const ADMIN_LIST_SUCCESS = "ADMIN_LIST_SUCCESS";
export const ADMIN_LIST_FAIL = "ADMIN_LIST_FAIL";

export const ADMIN_DETAILS_REQUEST = "ADMIN_DETAILS_REQUEST";
export const ADMIN_DETAILS_SUCCESS = "ADMIN_DETAILS_SUCCESS";
export const ADMIN_DETAILS_FAIL = "ADMIN_DETAILS_FAIL";

export const ADMIN_CREATE_REQUEST = "ADMIN_CREATE_REQUEST";
export const ADMIN_CREATE_SUCCESS = "ADMIN_CREATE_SUCCESS";
export const ADMIN_CREATE_FAIL = "ADMIN_CREATE_FAIL";
export const ADMIN_CREATE_RESET = "ADMIN_CREATE_RESET";

export const ADMIN_UPDATE_REQUEST = "ADMIN_UPDATE_REQUEST";
export const ADMIN_UPDATE_SUCCESS = "ADMIN_UPDATE_SUCCESS";
export const ADMIN_UPDATE_FAIL = "ADMIN_UPDATE_FAIL";
export const ADMIN_UPDATE_RESET = "ADMIN_UPDATE_RESET";
